//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dafuwongEntities : DbContext
    {
        public dafuwongEntities()
            : base("name=dafuwongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<manager> manager { get; set; }
        public virtual DbSet<manager_role> manager_role { get; set; }
        public virtual DbSet<manager_role_value> manager_role_value { get; set; }
        public virtual DbSet<navigation> navigation { get; set; }
        public virtual DbSet<tb_ChatDetail> tb_ChatDetail { get; set; }
        public virtual DbSet<tb_choushui> tb_choushui { get; set; }
        public virtual DbSet<tb_fankui> tb_fankui { get; set; }
        public virtual DbSet<tb_game_detail> tb_game_detail { get; set; }
        public virtual DbSet<tb_gameRecords> tb_gameRecords { get; set; }
        public virtual DbSet<tb_hongBao> tb_hongBao { get; set; }
        public virtual DbSet<tb_hongBaoLingQu> tb_hongBaoLingQu { get; set; }
        public virtual DbSet<tb_jiesuandetail> tb_jiesuandetail { get; set; }
        public virtual DbSet<tb_JinQiangBaoMsg> tb_JinQiangBaoMsg { get; set; }
        public virtual DbSet<tb_julebu> tb_julebu { get; set; }
        public virtual DbSet<tb_julebuuser> tb_julebuuser { get; set; }
        public virtual DbSet<tb_manager> tb_manager { get; set; }
        public virtual DbSet<tb_MsgList> tb_MsgList { get; set; }
        public virtual DbSet<tb_online> tb_online { get; set; }
        public virtual DbSet<tb_option_ticheng> tb_option_ticheng { get; set; }
        public virtual DbSet<tb_pay_order> tb_pay_order { get; set; }
        public virtual DbSet<tb_pipei_data> tb_pipei_data { get; set; }
        public virtual DbSet<tb_prompt> tb_prompt { get; set; }
        public virtual DbSet<tb_qunInfo> tb_qunInfo { get; set; }
        public virtual DbSet<tb_QunUser> tb_QunUser { get; set; }
        public virtual DbSet<tb_recharge> tb_recharge { get; set; }
        public virtual DbSet<tb_request> tb_request { get; set; }
        public virtual DbSet<tb_robot> tb_robot { get; set; }
        public virtual DbSet<tb_User> tb_User { get; set; }
        public virtual DbSet<tb_user_bank> tb_user_bank { get; set; }
        public virtual DbSet<tb_user_fangka> tb_user_fangka { get; set; }
        public virtual DbSet<tb_user_fanli> tb_user_fanli { get; set; }
        public virtual DbSet<tb_user_jiangli> tb_user_jiangli { get; set; }
        public virtual DbSet<tb_user_jiesuan> tb_user_jiesuan { get; set; }
        public virtual DbSet<tb_user_jinbi> tb_user_jinbi { get; set; }
        public virtual DbSet<tb_user_LeiDetail> tb_user_LeiDetail { get; set; }
        public virtual DbSet<tb_user_tixian> tb_user_tixian { get; set; }
        public virtual DbSet<tb_user_yaopai> tb_user_yaopai { get; set; }
        public virtual DbSet<tb_userjiesuan> tb_userjiesuan { get; set; }
        public virtual DbSet<tb_pay_pictures> tb_pay_pictures { get; set; }
        public virtual DbSet<tb_tixian_detail> tb_tixian_detail { get; set; }
    
        public virtual ObjectResult<getALLuser_Result> getALLuser(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getALLuser_Result>("getALLuser", uidParameter);
        }
    
        public virtual int getJi(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getJi", uidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetJulebuid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetJulebuid");
        }
    
        public virtual ObjectResult<getMsgList_Result> getMsgList(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMsgList_Result>("getMsgList", uidParameter);
        }
    
        public virtual ObjectResult<getUser_Result> getUser(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUser_Result>("getUser", uidParameter);
        }
    
        public virtual int GetUserDayYeJi(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetUserDayYeJi", dateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetUserWxid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetUserWxid");
        }
    
        public virtual ObjectResult<Nullable<int>> GETYaoqingma()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GETYaoqingma");
        }
    }
}
