//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChatDetail
    {
        public int id { get; set; }
        public Nullable<int> ChatType { get; set; }
        public Nullable<int> SendWxid { get; set; }
        public string SendUserName { get; set; }
        public string SendUserImage { get; set; }
        public Nullable<int> HongBaoId { get; set; }
        public string HongBaoName { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<int> qunId { get; set; }
        public string faName { get; set; }
        public string lingName { get; set; }
        public Nullable<int> lingWxid { get; set; }
    }
}
