//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_game_detail
    {
        public int id { get; set; }
        public Nullable<decimal> orderid { get; set; }
        public Nullable<decimal> orderdetailid { get; set; }
        public string openid { get; set; }
        public Nullable<int> roomid { get; set; }
        public Nullable<int> iszhuang { get; set; }
        public Nullable<int> ishu { get; set; }
        public Nullable<int> isting { get; set; }
        public Nullable<int> hufen { get; set; }
        public Nullable<int> gangfen { get; set; }
        public Nullable<int> caguafen { get; set; }
        public Nullable<int> zongfen { get; set; }
        public Nullable<int> gangcountming { get; set; }
        public Nullable<int> gangcountan { get; set; }
        public string pengganginfo { get; set; }
        public Nullable<System.DateTime> setdate { get; set; }
        public string gametype { get; set; }
        public Nullable<int> mashu { get; set; }
        public string caguainfo { get; set; }
        public string mypk { get; set; }
        public Nullable<int> fanshu { get; set; }
        public string fanshuname { get; set; }
        public Nullable<int> gen { get; set; }
        public Nullable<int> hutype { get; set; }
        public string dianpaouid { get; set; }
        public string zimouid { get; set; }
        public string chadajiaouid { get; set; }
        public Nullable<System.DateTime> hutime { get; set; }
        public string defendetail { get; set; }
        public string shufendetail { get; set; }
        public Nullable<int> huashu { get; set; }
        public Nullable<int> julebuid { get; set; }
        public Nullable<int> istaopao { get; set; }
        public Nullable<int> fzwxid { get; set; }
    }
}
