//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_hongBao
    {
        public int id { get; set; }
        public Nullable<int> wxid { get; set; }
        public Nullable<int> qunId { get; set; }
        public string hongBaoName { get; set; }
        public Nullable<int> curCount { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> leiDian { get; set; }
        public string listMoney { get; set; }
        public Nullable<System.DateTime> setdate { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> jinqiang { get; set; }
        public string uid { get; set; }
    }
}
