//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_julebuuser
    {
        public int id { get; set; }
        public Nullable<int> julebuid { get; set; }
        public string uid { get; set; }
        public string gametype { get; set; }
        public Nullable<System.DateTime> setdate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> integral { get; set; }
    }
}
