//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_manager
    {
        public int id { get; set; }
        public int role_type { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string real_name { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public Nullable<int> is_lock { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<int> dailiid { get; set; }
        public string pwd { get; set; }
        public Nullable<int> yaoqingma { get; set; }
        public int last_id { get; set; }
        public int fk { get; set; }
        public int status { get; set; }
        public Nullable<int> clubid { get; set; }
        public Nullable<int> number { get; set; }
        public string ip { get; set; }
        public string userid { get; set; }
        public Nullable<int> bling { get; set; }
        public string wx { get; set; }
        public Nullable<System.DateTime> last_time { get; set; }
        public Nullable<decimal> money { get; set; }
        public string gonggao { get; set; }
        public Nullable<int> fanli { get; set; }
        public Nullable<int> last_last_id { get; set; }
        public Nullable<int> type { get; set; }
        public string job { get; set; }
        public Nullable<int> percent { get; set; }
        public string name { get; set; }
        public string id_number { get; set; }
        public string alipay { get; set; }
        public string bank { get; set; }
        public string qrcode { get; set; }
    }
}
