//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pipei_data
    {
        public int id { get; set; }
        public string roomName { get; set; }
        public Nullable<int> roomNameNumber { get; set; }
        public Nullable<double> diFen { get; set; }
        public Nullable<int> roomdengji { get; set; }
        public Nullable<int> xianZhi { get; set; }
        public Nullable<int> gametype { get; set; }
    }
}
