//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pay_order
    {
        public int id { get; set; }
        public string orderid { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<int> addnum { get; set; }
        public Nullable<int> wxid { get; set; }
        public string customerip { get; set; }
        public string pingtai { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> setdate { get; set; }
        public string p5_orderid { get; set; }
        public Nullable<System.DateTime> paytime { get; set; }
        public string tuijianma { get; set; }
        public Nullable<int> zftype { get; set; }
    }
}
