//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_QunUser
    {
        public int id { get; set; }
        public Nullable<int> wxid { get; set; }
        public Nullable<int> qunId { get; set; }
        public Nullable<System.DateTime> setdate { get; set; }
        public Nullable<System.DateTime> aggreeTime { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> lastTime { get; set; }
    }
}
