//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_request
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> count { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> wxid { get; set; }
        public string type { get; set; }
        public string card_num { get; set; }
        public string telephone { get; set; }
    }
}
