//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_robot
    {
        public string uid { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<int> wxId { get; set; }
        public string username { get; set; }
        public string headimgurl { get; set; }
        public string sex { get; set; }
        public Nullable<decimal> jinbi { get; set; }
    }
}
