//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user_jiesuan
    {
        public int id { get; set; }
        public Nullable<decimal> orderid { get; set; }
        public string openid { get; set; }
        public Nullable<int> roomid { get; set; }
        public Nullable<int> zongdefen { get; set; }
        public Nullable<int> zimocount { get; set; }
        public Nullable<int> dianpaocount { get; set; }
        public Nullable<int> jiepaocount { get; set; }
        public Nullable<int> gangcountming { get; set; }
        public Nullable<int> gangcountan { get; set; }
        public Nullable<System.DateTime> setdate { get; set; }
        public string gametype { get; set; }
        public Nullable<int> isdaikai { get; set; }
        public Nullable<int> fzwxid { get; set; }
        public Nullable<int> maxscore { get; set; }
        public Nullable<int> julebuid { get; set; }
        public Nullable<int> collection { get; set; }
        public Nullable<int> fee { get; set; }
        public Nullable<decimal> tax { get; set; }
    }
}
