//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tryMJcard.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user_fanli
    {
        public int id { get; set; }
        public Nullable<int> tuijianma { get; set; }
        public string chongzhiuid { get; set; }
        public Nullable<decimal> prefanli { get; set; }
        public Nullable<decimal> addfanli { get; set; }
        public Nullable<decimal> currentfanli { get; set; }
        public Nullable<System.DateTime> setdate { get; set; }
        public string summary { get; set; }
        public Nullable<int> money { get; set; }
    }
}
